#services:
#  postgres:
#    image: 'postgres:${POSTGRES_TAG}'
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_USER: ${POSTGRES_USER}
#    ports:
#      - ${POSTGRES_PORT}
#    volumes:
#      - postgresdata:/data/db
#
#volumes:
#  postgresdata: