services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=${MONGO_DB}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}'
      - 'MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}'
    ports:
      - '27017:27017'
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata: