#services:
#  mysql:
#    image: 'mysql:${MYSQL_TAG}'
#    environment:
#      - 'MYSQL_DATABASE=${MYSQL_DB}'
#      - 'MYSQL_PASSWORD=${MYSQL_PASS}'
#      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}'
#      - 'MYSQL_USER=${MYSQL_USER}'
#    ports:
#      - '${MYSQL_PORT}'
#    volumes:
#      - mysqldata:/data/db
#
#volumes:
#  mysqldata: